language: go

go:
    - 1.7.x
    - tip

matrix:
    allow_failures:
        - go: tip

install:
  - rm -rf $GOPATH/src/srcd.works
  - mkdir -p $GOPATH/src/srcd.works
  - ln -s $PWD $GOPATH/src/srcd.works/go-billy.v1
  - cd $GOPATH/src/srcd.works/go-billy.v1
  - go get -v -t ./...

script:
  - cd $GOPATH/src/srcd.works/go-billy.v1
  - go test -v ./...
  - make test-coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
